[package]
name = "easy-scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.20"
scraper = "0.23.1"
tokio = { version = "1.36", features = ["full"] }
futures = "0.3"
rand = "0.9.1"
async-trait = "0.1"
unicode-width = "0.2.1"
[features]
default = []
output_html = []
